### PR TITLE
nixUnstable compatibility

### PR DESCRIPTION
**Pull request by roberth**
Allow building with nixUnstable.
Allows fixing #291 by upgrading the nix client to match the daemon whenever the protocol is broken.

TODO
 - [x] 2.3 testing
 - [x] 2.4 testing
 - [x] handle new log protocol on the backend (daemon!)

### CODE REVIEW

**Comment by Mic92** [comment]
Do you need testers for this PR? I could give this a go on my person ci infrastructure.

**Comment by roberth** [comment]
> Do you need testers for this PR? I could give this a go on my person ci infrastructure.

@Mic92 I really appreciate that.

I'm switching my own agents to this PR as well, although I'm sticking to Nix 2.3. nixUnstable is too eager to crash on my projects, but if yours aren't as susceptible perhaps you'll find something that isn't a Nix crash.

For Nix 2.3 you can use this branch like you would [normally use master](https://docs.hercules-ci.com/hercules-ci/getting-started/deploy/nixos/).

For nixUnstable you could either
 - set `services.hercules-ci-agent.package` to something like the `nixos-unstable-nixUnstable.x86_64-linux.hercules-ci-agent` attribute in `nix/ci.nix`
 - use hercules-ci-agent in a flake and set it to `hercules-ci-agent.packages.${system}.hercules-ci-agent-nixUnstable`

I should note that with this change, Hercules CI isn't flake-based yet and ca-derivations support is also untested.

**Comment by Mic92** [comment]
It looks like you forgot to push a cachix commit?

```
error: getting status of '/run/user/0/nixos-rebuild.drW0lU/result': No such file or directory
building the system configuration...
cachix> exporting https://github.com/hercules-ci/cachix (rev 10592c569e6475856e18db70e7fc0e6cfecea723) into /nix/store/yc0rj8n41hvsg76hrmjjdczl59m2yj7z-cachix-10592c5cachix> Initialized empty Git repository in /nix/store/yc0rj8n41hvsg76hrmjjdczl59m2yj7z-cachix-10592c5/.git/
cachix> remote: Enumerating objects: 3573, done.
cachix> remote: Counting objects: 100% (403/403), done.
cachix> remote: Compressing objects: 100% (273/273), done.
cachix> remote: Total 3573 (delta 218), reused 239 (delta 118), pack-reused 3170
cachix> Receiving objects: 100% (3573/3573), 2.17 MiB | 17.25 MiB/s, done.
cachix> Resolving deltas: 100% (2063/2063), done.
cachix> From https://github.com/hercules-ci/cachixcachix>  * [new branch]      0.1.1                  -> origin/0.1.1
cachix>  * [new branch]      allow-exitSuccess      -> origin/allow-exitSuccess
cachix>  * [new branch]      angerman-feedback      -> origin/angerman-feedback
cachix>  * [new branch]      build-cachix-in-ci     -> origin/build-cachix-in-ci
cachix>  * [new branch]      build-tool-depnds      -> origin/build-tool-depnds
cachix>  * [new branch]      bulk-query             -> origin/bulk-query
cachix>  * [new branch]      bulk-query-store-path  -> origin/bulk-query-store-path
cachix>  * [new branch]      bump-actions           -> origin/bump-actions
cachix>  * [new branch]      bump-cachix-stable     -> origin/bump-cachix-stable
cachix>  * [new branch]      bump-nixpkgs           -> origin/bump-nixpkgs
cachix>  * [new branch]      cabal-fixes            -> origin/cabal-fixes
cachix>  * [new branch]      cachix-action-v3       -> origin/cachix-action-v3
cachix>  * [new branch]      cachix-api-v0.1.0.3    -> origin/cachix-api-v0.1.0.3
cachix>  * [new branch]      cli-option-config-path -> origin/cli-option-config-path
cachix>  * [new branch]      compression-level      -> origin/compression-level
cachix>  * [new branch]      conduit-combinators    -> origin/conduit-combinators
cachix>  * [new branch]      cplusplus              -> origin/cplusplus
cachix>  * [new branch]      darwin-cpp             -> origin/darwin-cpp
cachix>  * [new branch]      debug-closure          -> origin/debug-closure
cachix>  * [new branch]      debug-closure-2        -> origin/debug-closure-2
cachix>  * [new branch]      delete                 -> origin/delete
cachix>  * [new branch]      dependabot/github_actions/cachix/cachix-action-10 -> origin/dependabot/github_actions/cachix/cachix-action-10
cachix>  * [new branch]      dependabot/github_actions/cachix/install-nix-action-13 -> origin/dependabot/github_actions/cachix/install-nix-action-13
cachix>  * [new branch]      ditch-hpack            -> origin/ditch-hpack
cachix>  * [new branch]      domenkozar-patch-1     -> origin/domenkozar-patch-1
cachix>  * [new branch]      domenkozar-patch-1-1   -> origin/domenkozar-patch-1-1
cachix>  * [new branch]      dont-install-test-data -> origin/dont-install-test-data
cachix>  * [new branch]      empty-stdin            -> origin/empty-stdin
cachix>  * [new branch]      error-handling         -> origin/error-handling
cachix>  * [new branch]      export-keys            -> origin/export-keys
cachix>  * [new branch]      expose-http-manager    -> origin/expose-http-manager
cachix>  * [new branch]      fix-build              -> origin/fix-build
cachix>  * [new branch]      fix-ci                 -> origin/fix-ci
cachix>  * [new branch]      fix-eval-macos         -> origin/fix-eval-macos
cachix>  * [new branch]      fix-h-option           -> origin/fix-h-option
cachix>  * [new branch]      fix-hang               -> origin/fix-hang
cachix>  * [new branch]      fix-head               -> origin/fix-head
cachix>  * [new branch]      fix-newline-formatting -> origin/fix-newline-formatting
cachix>  * [new branch]      fix-tests              -> origin/fix-tests
cachix>  * [new branch]      fix-warnings           -> origin/fix-warnings
cachix>  * [new branch]      fsnotify-0.3           -> origin/fsnotify-0.3
cachix>  * [new branch]      github-actions         -> origin/github-actions
cachix>  * [new branch]      github-trust-cache     -> origin/github-trust-cache
cachix>  * [new branch]      group-error            -> origin/group-error
cachix>  * [new branch]      hlint                  -> origin/hlint
cachix>  * [new branch]      hotfix-nixos           -> origin/hotfix-nixos
cachix>  * [new branch]      install-api            -> origin/install-api
cachix>  * [new branch]      issue-120              -> origin/issue-120
cachix>  * [new branch]      issue-137              -> origin/issue-137
cachix>  * [new branch]      issue-258-watch-store-swallows-exc -> origin/issue-258-watch-store-swallows-exc
cachix>  * [new branch]      issue-28               -> origin/issue-28
cachix>  * [new branch]      issue-30               -> origin/issue-30
cachix>  * [new branch]      issue-56               -> origin/issue-56
cachix>  * [new branch]      issue-69               -> origin/issue-69
cachix>  * [new branch]      issue-70               -> origin/issue-70
cachix>  * [new branch]      issue-77-retry-transient-errors -> origin/issue-77-retry-transient-errors
cachix>  * [new branch]      just-jwt               -> origin/just-jwt
cachix>  * [new branch]      logout                 -> origin/logout
cachix>  * [new branch]      lts-11.12              -> origin/lts-11.12
cachix>  * [new branch]      lts-11.14              -> origin/lts-11.14
cachix>  * [new branch]      lts-12                 -> origin/lts-12
cachix>  * [new branch]      lts-12.0               -> origin/lts-12.0
cachix>  * [new branch]      lts-13-servant-ghc-8.6 -> origin/lts-13-servant-ghc-8.6
cachix>  * [new branch]      lts-13.30              -> origin/lts-13.30
cachix>  * [new branch]      lts-14.0               -> origin/lts-14.0
cachix>  * [new branch]      macos                  -> origin/macos
cachix>  * [new branch]      macos-failure-old-nix  -> origin/macos-failure-old-nix
cachix>  * [new branch]      master                 -> origin/master
cachix>  * [new branch]      narID                  -> origin/narID
cachix>  * [new branch]      narURL                 -> origin/narURL
cachix>  * [new branch]      netrc-create-missing-dir -> origin/netrc-create-missing-dir
cachix>  * [new branch]      nix-1.0                -> origin/nix-1.0
cachix>  * [new branch]      nixUnstable            -> origin/nixUnstable
cachix>  * [new branch]      nix_2.3                -> origin/nix_2.3
cachix>  * [new branch]      nixpkgs-bump           -> origin/nixpkgs-bump
cachix>  * [new branch]      noimplicitprelude      -> origin/noimplicitprelude
cachix>  * [new branch]      omit-deriver           -> origin/omit-deriver
cachix>  * [new branch]      optimize-servant-generic -> origin/optimize-servant-generic
cachix>  * [new branch]      pre-commit-hooks       -> origin/pre-commit-hooks
cachix>  * [new branch]      print-store-size       -> origin/print-store-size
cachix>  * [new branch]      private-caches         -> origin/private-caches
cachix>  * [new branch]      profiling-and-cnix-store -> origin/profiling-and-cnix-store
cachix>  * [new branch]      protolude-0.3          -> origin/protolude-0.3
cachix>  * [new branch]      push-latest-key        -> origin/push-latest-key
cachix>  * [new branch]      readme                 -> origin/readme
cachix>  * [new branch]      readme-link-changelogs -> origin/readme-link-changelogs
cachix>  * [new branch]      readme-logo-resize     -> origin/readme-logo-resize
cachix>  * [new branch]      redundant-warning      -> origin/redundant-warning
cachix>  * [new branch]      refactor-envless-lib   -> origin/refactor-envless-lib
cachix>  * [new branch]      refactor-use           -> origin/refactor-use
cachix>  * [new branch]      release-0.1            -> origin/release-0.1
cachix>  * [new branch]      release-0.1.0.1        -> origin/release-0.1.0.1
cachix>  * [new branch]      release-process        -> origin/release-process
cachix>  * [new branch]      release-process-fixes  -> origin/release-process-fixes
cachix>  * [new branch]      remove-auth-server-dep -> origin/remove-auth-server-dep
cachix>  * [new branch]      remove-safesemaphore   -> origin/remove-safesemaphore
cachix>  * [new branch]      revert-lts-13          -> origin/revert-lts-13
cachix>  * [new branch]      revert-nar             -> origin/revert-nar
cachix>  * [new branch]      rewrite-installation-mode-guesstimation -> origin/rewrite-installation-mode-guesstimation
cachix>  * [new branch]      sandbox                -> origin/sandbox
cachix>  * [new branch]      servant-0.14.1         -> origin/servant-0.14.1
cachix>  * [new branch]      servant-0.16           -> origin/servant-0.16
cachix>  * [new branch]      serve-nar              -> origin/serve-nar
cachix>  * [new branch]      shell-completion       -> origin/shell-completion
cachix>  * [new branch]      simplification         -> origin/simplification
cachix>  * [new branch]      smallfixes             -> origin/smallfixes
cachix>  * [new branch]      stack2nix              -> origin/stack2nix
cachix>  * [new branch]      storage-total          -> origin/storage-total
cachix>  * [new branch]      storepath-size         -> origin/storepath-size
cachix>  * [new branch]      sudo-nixos-rebuild     -> origin/sudo-nixos-rebuild
cachix>  * [new branch]      sync-to-push           -> origin/sync-to-push
cachix>  * [new branch]      tooling-nix-2.3        -> origin/tooling-nix-2.3
cachix>  * [new branch]      travis-ci              -> origin/travis-ci
cachix>  * [new branch]      travis-com             -> origin/travis-com
cachix>  * [new branch]      travis-simplify        -> origin/travis-simplify
cachix>  * [new branch]      update                 -> origin/update
cachix>  * [new branch]      update-for-nix-2.3     -> origin/update-for-nix-2.3
cachix>  * [new branch]      update-pre-commit      -> origin/update-pre-commit
cachix>  * [new branch]      update-readme          -> origin/update-readme
cachix>  * [new branch]      user-extra-field       -> origin/user-extra-field
cachix>  * [new branch]      v0.1.2                 -> origin/v0.1.2
cachix>  * [new branch]      v0.1.3                 -> origin/v0.1.3
cachix>  * [new branch]      v0.1.4                 -> origin/v0.1.4
cachix>  * [new branch]      v0.2.0                 -> origin/v0.2.0
cachix>  * [new branch]      v0.2.1                 -> origin/v0.2.1
cachix>  * [new branch]      v0.3.0                 -> origin/v0.3.0
cachix>  * [new branch]      version                -> origin/version
cachix>  * [new branch]      warnings               -> origin/warnings
cachix>  * [new tag]         cachix-0.6.0           -> cachix-0.6.0
cachix>  * [new tag]         cachix-api-0.1.0.3     -> cachix-api-0.1.0.3
cachix>  * [new tag]         gcroots/profiling-and-cnix-store-1 -> gcroots/profiling-and-cnix-store-1
cachix>  * [new tag]         v0.1.0.0               -> v0.1.0.0
cachix>  * [new tag]         v0.1.0.1               -> v0.1.0.1
cachix>  * [new tag]         v0.1.0.2               -> v0.1.0.2
cachix>  * [new tag]         v0.1.1                 -> v0.1.1
cachix>  * [new tag]         v0.1.2                 -> v0.1.2
cachix>  * [new tag]         v0.1.3                 -> v0.1.3
cachix>  * [new tag]         v0.2.0                 -> v0.2.0
cachix>  * [new tag]         v0.2.1                 -> v0.2.1
cachix>  * [new tag]         v0.3.0                 -> v0.3.0
cachix>  * [new tag]         v0.3.1                 -> v0.3.1
cachix>  * [new tag]         v0.3.2                 -> v0.3.2
cachix>  * [new tag]         v0.3.3                 -> v0.3.3
cachix>  * [new tag]         v0.3.4                 -> v0.3.4
cachix>  * [new tag]         v0.3.5                 -> v0.3.5
cachix>  * [new tag]         v0.3.6                 -> v0.3.6
cachix>  * [new tag]         v0.3.7                 -> v0.3.7
cachix>  * [new tag]         v0.3.8                 -> v0.3.8
cachix>  * [new tag]         v0.4.0                 -> v0.4.0
cachix>  * [new tag]         v0.5.0                 -> v0.5.0
cachix>  * [new tag]         v0.5.1                 -> v0.5.1
cachix>  * [new tag]         v0.6.0                 -> v0.6.0
cachix> fatal: git cat-file: could not get object info
cachix> Unrecognized git object type:
cachix> Unable to checkout 10592c569e6475856e18db70e7fc0e6cfecea723 from https://github.com/hercules-ci/cachix.
```

**Comment by roberth** [comment]
> It looks like you forgot to push a cachix commit?

Fixed it and added a tag to make sure the new hash is preserved in case I need to force push again

**Comment by Mic92** [comment]
error: hash mismatch in fixed-output derivation '/nix/store/nbb4mslwi3hj426a94wcvrgpfl3adgv9-cachix-f24e304.drv':
         specified: sha256-lTz/KlJZnuFgpdXSOqABtgGVBQUsgYBvYKE23bAgPf4=
            got:    sha256-A1fyUhMQqFPzop+agH3DsmrD8DQgag1BMz5Arzp9q+w=

**Comment by roberth** [comment]
My bad. :see_no_evil:  I've updated the hash.

**Comment by Mic92** [comment]
Works for me so far! Also have a simple nix flake hack here: https://github.com/Mic92/dotfiles/blob/master/ci.nix

**Comment by Mic92** [comment]
The flakes hack still works for me. Might be worth documenting.

**Pull request merged**
