### PR TITLE
darwin: build on nixos-unstable

### PR DESCRIPTION
**Pull request by domenkozar**
- [ ] https://github.com/NixOS/nixpkgs/pull/64286/files

### CODE REVIEW

**Comment by domenkozar** [comment]
Not sure how to fix this, cachix is failing like it's not applying  the C++14 standard.

**Comment by domenkozar** [comment]
found the issue:  cachix/agent need to be built with `llvmPackages_6.clang`

**Comment by roberth** [comment]
It's not built on master, see https://hercules-ci.com/github/hercules-ci/hercules-ci-agent/jobs/477

**Comment by domenkozar** [comment]
Yes, but I'm going to open a new PR.

**Comment by roberth** [comment]
I thought this was an issue. Sorry about that.

**Pull request closed without merging**
